BrofessorTec/SE1Mineswepper

- Mineswepper/mineswepper/NameDoc.txt
Updating dev with my branch where i added discord name
> adding discord name to name doc

- ContributeDoc.txt
> removed doc

- Mineswepper.js
- index.html
- style.css
coded, noted and tested.. basic css and html done
> Sprint1 christian r javascript

- index.html
- style.css
added div for game frame as well as individual divs for each segment within the frame
> Sprint2_ScottyGameFrame

- Mineswepper.js
- index.html
- style.css
fixed display issues, added gap and grid display attribute to css. changed gridRows and gridCols to fit to frame. Changed class and id names to better match what they do. game-board -> Frame, game -> game-board.
> Fixed Grid display issues

- index.html
- rules.html
- style.css
1. Created a seperate page for the rules. I did this because I figure that is how it will ultimately be viewed when it ends up in a navbar or maybe we could put it in a modal later as well.  Either way, it is distinctly seperated this way for the time being.
2.  Added a temporary button on the index to get to the rules page.
3.  Added styles for the rules page and the temp button in styles.css.
> Create ruleset page and add temporary button to index

- Mineswepper.js
> Adding Unique Mine location logic

- Tile.js
Tile Class Addition with 2D array function
> Tile Class Addition

- Mineswepper.js
- style.css
Applied the color scheme to the frame, grid, and cells (unrevealed, revealed, and bombs)
> Applying color scheme

- Mineswepper.js
- Tile.js
- index.html
Refactored code to work the same as before, but now using the Tile class and it's functions and fields. Can click to reveal tiles with the correct CSS and it will display the number of neighboring Mines or a Mine itself. Mine generation and placing is implemented, but the number neighbors logic is not yet.
> Implemented Tile Class usage. 

- Mineswepper.js
- Tile.js
- tests/unit/TestRunner.js
- tests/unit/Tile.test.js
- In the new tests directory there is 'unit' and 'integration'. Integration is currently empty, but I plan to work on that later.
- Created Tile.js unit tests by manually mocking the DOM and testing anticipated output. In the real world, we would most likely be using a cushy testing framework like Jest, but in effort to minimize external package dependency, I amdoing it the gross way. Type `node .\TestRunner.js in CLI to run tests.`
- Small change to Tile.js in the reveal function to give domElement.textContent actual text rather than dynamic reference. Better for testing and doesn't effect implementation.
- Exported objects and functions from both Tile.js and Mineswepper.js in order to access them for unit testing.
> unit tests initial

- Tile.js
- style.css
Reverts flag feature to allow bomb PR to be merged first. Will then add my code to that once merged
> Revert "Flag Feature"

- Mineswepper.js
- Tile.js
Added bomb functionality, game will now reveal all bombs when one is revealed and prevent the player from continuing. This process was much more involved than I initially anticipated and required a lot of minor changes to pre-existing functions and methods. I also tried to correct the spacing for some lines as they were indented a little strangely in some places and I have OCD
> Sprint3_ScottyBombFunctionality

- Tile.js
- style.css
> FlagAfterBomb

- Mineswepper.js
- Tile.js
Went through and made some small changes like capitalization on some comments to make it look cleaner
Also had to adjust the number functionality feature as without the changes it was giving some bugs such as being able to click the tiles again and increasing the number, as well as not working well with the first click, tried various different approaches to it and after about 2-3 hours of messing with it, the only solution was to edit the checkNeighborMines to a different format.
this is why I put in the title that atleast 2 people should review this one
If anyone has any better ideas feel free to update branch this before we send it to dev (just don't break it)
> ATLEAST 2 PEOPLE REVIEW- First Click and Number Functionality Into Epic Branch 

- Mineswepper.js
- index.html
- style.css
Added the timer which 
-Starts on the first click
-Stops if the game ends (when mine is hit)
-Stops at 9:59 (stays as 3 digits)
> Added timer with full functionality

- Mineswepper.js
- Tile.js
added the feature to reveal all adjacent " " tiles when clicking a " " tile
the issue is with only 10 bombs and a 10x10 grid it reveals alot so we might need to adjust the bomb count soon
> Sprint4 adjacent tiles Zach Farmer

- index.html
The temporary rules button was commented out and all team member names were added to the credit section.
> Commented out the temporary rule button and added the credits section

- Mineswepper.js
- Tile.js
- index.html
- style.css
There is no limit to the flags, but the flag count is working properly
> Sprint4 Zach Farmer Flag Count

- main.py
> Selenium File

- Mineswepper.js
- index.html
- style.css
Added the Mine counter to the main page below the timer
> Sprint4 mine counter Gavin f

- Mineswepper.js
- Tile.js
- index.html
> added name input feature
